# Generated by Django 6.0.3 on 2026-04-14 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='boardmembership',
            old_name='joined_date',
            new_name='joined_at',
        ),
        migrations.RemoveField(
            model_name='board',
            name='description',
        ),
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardmembership',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='board_app.board'),
        ),
        migrations.AlterUniqueTogether(
            name='boardmembership',
            unique_together={('user', 'board')},
        ),
    ]
