# Generated by Django 6.0.3 on 2026-04-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_rename_name_board_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], max_length=10),
        ),
    ]
